server:
  port: 8888
  
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///C:/config2
          uri: https://github.com/hiksyksy1234/spring-cloud-config.git
          default-label: main  #main branch
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh  
