server:
  port: 0
  
spring:
  application:
    name: board-service
  datasource: 
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@oracle-server:1521/xe
    username: scott
    password: tiger  
    
    
eureka:
  client:
    register-with-eureka: true
    fetch-regisry: true
    service-url.defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}


mybatis:
  type-aliases-package: com.naver.myhome4.domain
  config-location: classpath:/com/naver/myhome4/mybatis/config/mybatis-config.xml
  mapper-locations: classpath:/com/naver/myhome4/mybatis/mapper/*.xml
    
# mapper log print
logging:
  level:
    root: info
    com:
      naver:
        myhome4:
          mybatis:
            mapper:
              BoardMapper: trace
          client: debug   


my:
 savefolder: c:/upload


token:
 secret: access_Token
